# Question 1

In [1]:
import numpy as np

In [120]:
data_2016 = np.genfromtxt("AAPL-2016.csv",delimiter=",")
data_2017 = np.genfromtxt("AAPL-2017.csv",delimiter=",")
data_2016 = data_2016[1:,1:]
data_2017 = data_2017[2:,1:]
print(data_2016.shape)
print(data_2017.shape)

(250, 6)
(250, 6)


In [113]:
price_volume_2016 = data_2016[:,[4,6]]
price_volume_2017 = data_2017[:,[4,6]]

In [114]:
# axis of 0 sums down the columns
print(price_volume_2016.sum(axis=0))
print(price_volume_2017.sum(axis=0))

[ 26127.66  9634995700.00]
[ 37672.17  6781644300.00]


# Question 2

In [115]:
change = price_volume_2017 - price_volume_2016
print(change.sum(axis=0))

[ 11544.51 -2853351400.00]


# Question 3

In [116]:
print(change)
np.set_printoptions(formatter={"float": "{: 6.2f}".format})
print(change)

[[ 10.67 -46531300.00]
 [ 13.90 -33597400.00]
 [ 17.21 -36705500.00]
 [ 22.54 -47532500.00]
 [ 22.15 -46335900.00]
 [ 21.22 -22150800.00]
 [ 19.29 -22068000.00]
 [ 21.65 -36327700.00]
 [ 20.48 -28730300.00]
 [ 22.86 -55297000.00]
 [ 23.12 -27490400.00]
 [ 23.21 -39736500.00]
 [ 23.78 -30111300.00]
 [ 18.55 -42589500.00]
 [ 22.44 -19416900.00]
 [ 21.95 -48739400.00]
 [ 28.53 -112806800.00]
 [ 27.54 -25301300.00]
 [ 24.01 -15215500.00]
 [ 32.32  71041500.00]
 [ 34.05 -3646800.00]
 [ 32.73 -21457000.00]
 [ 33.69 -19625800.00]
 [ 37.51 -8234300.00]
 [ 37.03 -31017300.00]
 [ 37.43 -15981300.00]
 [ 37.85 -22278100.00]
 [ 39.59 -27039300.00]
 [ 41.03 -7125200.00]
 [ 38.87 -13434800.00]
 [ 37.23 -22278600.00]
 [ 39.46 -16822800.00]
 [ 40.66 -10867000.00]
 [ 40.23 -13443900.00]
 [ 41.84 -11154400.00]
 [ 40.56 -14479100.00]
 [ 40.17 -7325300.00]
 [ 40.08 -5508200.00]
 [ 43.10  1198300.00]
 [ 38.43 -24196100.00]
 [ 39.03 -12061500.00]
 [ 37.84 -15205700.00]
 [ 36.51 -28608800.00]
 [ 37.13 -171217

# Question 4

In [121]:
combined_years = np.concatenate((data_2016,data_2017))
print(combined_years)

[[ 102.61  105.37  102.00  105.35  100.27  67649400.00]
 [ 105.75  105.85  102.41  102.71  97.76  55791000.00]
 [ 100.56  102.37  99.87  100.70  95.85  68457400.00]
 ...
 [ 170.10  170.78  169.71  170.60  168.66  21498200.00]
 [ 171.00  171.85  170.48  171.08  169.14  16480200.00]
 [ 170.52  170.59  169.22  169.23  167.31  25884400.00]]


# Question 5

In [122]:
np.savetxt("combined_years.txt",combined_years,delimiter=",",fmt="%10.2f")