# Data Science Introduction

We will be using two additional packages - `numpy` and `pandas`. They both need to be imported and usually they are given an alias.

In [1]:
import pandas as pd
import numpy as np

## Numpy array

Example of numpy `array` structure.

In [2]:
a = np.array([1,2,3])
print(a)

[1 2 3]


The array `a` has a special `ndarray` type.

In [3]:
print(type(a))

<class 'numpy.ndarray'>


In [4]:
print(type(a[0]))

<class 'numpy.int32'>


Check the dimension and size of the array.

In [5]:
a.shape

(3,)

Create a multidimensional array.

In [6]:
b = np.array([[1,2,3],[4,5,6],[7,8,9]], dtype=np.float64)
print(b)

[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


In [7]:
print(type(b))

<class 'numpy.ndarray'>


In [8]:
b.shape

(3, 3)

In [9]:
print(type(b[0][0]))

<class 'numpy.float64'>


The `strides` attributes gives us the number of bytes to step in each direction when traversing the array. 

In [10]:
b.strides
#8 bytes to reach the next column and 24 bytes to reach the next row

(24, 8)

Zero-dimensional array - scalar.

In [11]:
x = np.array(42)
print(x)
print(type(x))
print(np.ndim(x))
print(x.shape)

42
<class 'numpy.ndarray'>
0
()


In [12]:
arr = np.array([1,'martina', 7.8])
print(arr)
print(type(arr[0]))

['1' 'martina' '7.8']
<class 'numpy.str_'>


### Special arrays

Arrays of ones and zeroes

In [ ]:
ones = np.ones((2,3), float)
print(ones)

In [ ]:
zeroes = np.zeros((2,3), int)
print(zeroes)

Identity arrays

In [13]:
ident = np.identity(3)
print(ident)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


Non-square identity matrix, the `k` parameter defines the position of the diagonal, default 0 - main diagonal.

In [14]:
ident2 = np.eye(3,4,k=2, dtype=int)
print(ident2)

[[0 0 1 0]
 [0 0 0 1]
 [0 0 0 0]]


### Numerical operations

Use standard mathematical notation for adding, subtracting and comparing entire arrays.

** NO NEED TO LOOP OVER EACH VALUE **

In [15]:
a = np.array([1,2,3,4,5,6,7,8])
a = a + 1
print(a)

[2 3 4 5 6 7 8 9]


In [ ]:
# adding two arrays together
b = np.ones((1,8), int)
print(b)

c = a+b
print(c)

Matrix multiplication

In [ ]:
mat1 = np.array([[1,2,3], [4,5,6]])
mat2 = np.array([[1,2], [3,4], [5,6]])
print(np.dot(mat1,mat2))

Equality operator

In [ ]:
mat1 = np.array([[1,2,4], [3,4,5], [6,7,8]])
mat2 = np.array([[1,2,6],[3,7,5], [6,4,5]])
print(mat1 == mat2)

#complete array equality
print(np.array_equal(mat1, mat2))

Mathematical comparison

In [ ]:
arr1 = np.array ([1,2,3,4,5])
# same for comparisons
#arr1 > arr2
#arr1 < arr2
#arr1 <= arr2
#arr1 >= arr2
#arr1 == arr2
#arr1 != arr2

# and also more complex expressions
(arr1 + 12) >= 15
#(arr2 - arr1) == 27

Boolean operators

In [ ]:
np.logical_or(  (arr1 % 2) == 0, (arr2 % 20) == 0 )

#np.logical_and( (arr1 % 2) == 0, (arr2 % 20) == 0 )

#np.logical_not( (arr1 % 2) == 0 )

Structured arrays - heterogenous data

In [21]:
dt = np.dtype([('country', 'S20'), ('population','i4')])
datatable = np.array([
    ('UK', 65640000),
    ('USA', 323100000),
    ('Russia', 144300000)
], dtype = dt)

print(datatable)

[(b'UK',  65640000) (b'USA', 323100000) (b'Russia', 144300000)]


In [22]:
print(datatable['country'])

[b'UK' b'USA' b'Russia']


In [ ]:
print(datatable['population'])

In [ ]:
ctry = datatable[0]
print(ctry)
print(ctry[0])

Numpy matrices are strictly 2-D, support matrix manipulation

In [ ]:
MA = np.mat([[1,2,3], [4,5,6]])
MB = np.mat([[7,8],[9,12],[10,11]])

print(MA*MB)

## Numpy arange

Example of `arange()` function, if used with integers it is almost equivalent to Python in-built `range()` function. The values are generated within the half-open interval, similar to slicing.

In [ ]:
a = np.arange(1,5)
print(a)

Using optional step-size parameter.

In [ ]:
a = np.arange(0.5, 2.5, 0.5)
print(a)
print(type(a))

## Pandas DataFrames

 - DataFrames are rectangular table of data
 - Contain rows and columns
 - Columns have headings
 - Rows have index

In [17]:
# can create dataframe by reading an excel spreadsheet
df = pd.read_excel(io='FinData.xls', sheet_name='AMZN')
df

Date         Open         High          Low        Close  \
0   2020-10-26  3198.739990  3282.979980  3153.300049  3207.040039   
1   2020-10-27  3224.939941  3291.659912  3211.300049  3286.330078   
2   2020-10-28  3249.300049  3264.020020  3162.469971  3162.780029   
3   2020-10-29  3201.270020  3257.250000  3164.000000  3211.010010   
4   2020-10-30  3157.750000  3167.000000  3019.000000  3036.149902   
..         ...          ...          ...          ...          ...   
247 2021-10-19  3434.290039  3454.689941  3422.000000  3444.149902   
248 2021-10-20  3452.659912  3462.860107  3400.370117  3415.060059   
249 2021-10-21  3414.250000  3440.280029  3403.000000  3435.010010   
250 2021-10-22  3421.000000  3429.840088  3331.300049  3335.550049   
251 2021-10-25  3335.000000  3347.800049  3297.699951  3320.370117   

       Adj Close   Volume  
0    3207.040039  5901200  
1    3286.330078  4291000  
2    3162.780029  5588300  
3    3211.010010  6596500  
4    3036.149902  8386400  
..           ...      ...  
247  3444.149902  2386100  
248  3415.060059  2139800  
249  3435.010010  1881400  
250  3335.550049  3133800  
251  3320.370117  2222700  

[252 rows x 7 columns]

View first few rows or last few rows.

In [18]:
df.head()

Date         Open         High          Low        Close    Adj Close  \
0 2020-10-26  3198.739990  3282.979980  3153.300049  3207.040039  3207.040039   
1 2020-10-27  3224.939941  3291.659912  3211.300049  3286.330078  3286.330078   
2 2020-10-28  3249.300049  3264.020020  3162.469971  3162.780029  3162.780029   
3 2020-10-29  3201.270020  3257.250000  3164.000000  3211.010010  3211.010010   
4 2020-10-30  3157.750000  3167.000000  3019.000000  3036.149902  3036.149902   

    Volume  
0  5901200  
1  4291000  
2  5588300  
3  6596500  
4  8386400

In [19]:
df.tail(10)

Date         Open         High          Low        Close  \
242 2021-10-12  3257.000000  3267.530029  3236.280029  3247.330078   
243 2021-10-13  3269.709961  3288.379883  3261.090088  3284.280029   
244 2021-10-14  3302.449951  3312.600098  3290.780029  3299.860107   
245 2021-10-15  3311.419922  3410.419922  3304.000000  3409.020020   
246 2021-10-18  3388.360107  3449.169922  3385.100098  3446.739990   
247 2021-10-19  3434.290039  3454.689941  3422.000000  3444.149902   
248 2021-10-20  3452.659912  3462.860107  3400.370117  3415.060059   
249 2021-10-21  3414.250000  3440.280029  3403.000000  3435.010010   
250 2021-10-22  3421.000000  3429.840088  3331.300049  3335.550049   
251 2021-10-25  3335.000000  3347.800049  3297.699951  3320.370117   

       Adj Close   Volume  
242  3247.330078  1819600  
243  3284.280029  2420100  
244  3299.860107  2109500  
245  3409.020020  5175100  
246  3446.739990  3174100  
247  3444.149902  2386100  
248  3415.060059  2139800  
249  3435.010010  1881400  
250  3335.550049  3133800  
251  3320.370117  2222700

Access certain columns

In [ ]:
df['Open']

In [ ]:
print(type(df['Open']))

In [ ]:
df[['Open']]

In [ ]:
print(type(df[['Open']]))

In [ ]:
#multiple columns
df[['Open', 'Close', 'Adj Close']]

Using filters

In [ ]:
# filter
df['Open'] > 3000

#using filter
df[df['Open']>3000]

Getting rows

In [ ]:
# check the type
df.loc[1]

In [ ]:
# data frame
df.loc[[1]]

In [ ]:
df.loc[5:90]

Functions on columns of data:
- min
- max
- mean
- median
- count

Min and max also work on string columns.

In [ ]:
df['Open'].mean()
#df['Open'].min()
#df['Open'].max()
#df['Open'].median()
#df['Open'].max()
#df['Open'].count()

In [ ]:
df[['Open', 'Close', 'Adj Close']].mean()

Array arithmetics with DataFrame

In [ ]:
df['Open'] - df['Close']

In [ ]:
arr = df['High'] > 3020
print(arr[6:90])

## Numpy where

In [ ]:
a = np.array([1,2,3,4,5])
np.where(a % 2 == 0, 'Even', 'Odd')

In [20]:
np.where(df['High'] > 3100 , 'High', 'Low')

array(['High', 'High', 'High', 'High', 'High', 'Low', 'Low', 'High',
       'High', 'High', 'High', 'High', 'High', 'High', 'High', 'High',
       'High', 'High', 'High', 'High', 'High', 'High', 'High', 'High',
       'High', 'High', 'High', 'High', 'High', 'High', 'High', 'High',
       'High', 'High', 'High', 'High', 'High', 'High', 'High', 'High',
       'High', 'High', 'High', 'High', 'High', 'High', 'High', 'High',
       'High', 'High', 'High', 'High', 'High', 'High', 'High', 'High',
       'High', 'High', 'High', 'High', 'High', 'High', 'High', 'High',
       'High', 'High', 'High', 'High', 'High', 'High', 'High', 'High',
       'High', 'High', 'High', 'High', 'High', 'High', 'High', 'High',
       'High', 'High', 'High', 'High', 'High', 'High', 'High', 'High',
       'Low', 'Low', 'Low', 'Low', 'High', 'High', 'Low', 'Low', 'High',
       'High', 'High', 'Low', 'High', 'High', 'High', 'High', 'Low',
       'Low', 'Low', 'High', 'High', 'High', 'High', 'High', 'High',
       'Hi

## Time Series

In [ ]:
df = pd.read_excel(io='FinData.xls', sheet_name='DARK.L', index_col = 'Date', parse_dates = True)
df

In [ ]:
df.describe()

In [ ]:
df['2021-10']

In [ ]:
df['2021-May':'2021-Sep']


In [ ]:
df['2021-May':'2021-Sep':30]

In [ ]:
df['Open'].plot()

In [ ]:
open = df[['Open']]

In [ ]:
open['2021-May':'2021-Aug'].plot()

In [ ]:
df2 = df[['Open','Close']]
df2['2021-May':'2021-Aug'].plot()